export const allProducts = [
  {
    id: 1,
    name: "Collagen Gummies",
    characteristics: [
      "Helps speed up and normalize the digestion process",
      "Assists in healthy weight loss without a negative impact on your health",
      "Helps speed up and normalize the digestion process",
      "Assists in healthy weight loss without a negative impact on your health",
      "Increases the reserves of energy in your body",
      "Safe with no side effects",
      "Controls blood sugar levels",
      "Help keep your muscles lean",
      "Helps improve cognitive functions",
    ],
    description: "",
    extraInfo: "GMO-free",
    relatedProductsId: [2, 3, 4],
    optionsId: [1, 2, 3, 4, 5],
    price: { 1: 39.95, 2: 39.95 },
    imgSrc: "/images/Daily-Herbals-Collagen.jpeg",
  },
  {
    id: 2,
    name: "Cleanse Pro",
    characteristics: [
      "Helps speed up and normalize the digestion process",
      "Assists in healthy weight loss without a negative impact on your health",
      "Helps speed up and normalize the digestion process",
      "Assists in healthy weight loss without a negative impact on your health",
      "Increases the reserves of energy in your body",
      "Safe with no side effects",
      "Controls blood sugar levels",
      "Help keep your muscles lean",
      "Helps improve cognitive functions",
    ],
    description:
      "Ingredients: Flaxseed 400mg (40%), Oat Bran 300mg (30%), Papya Leaf Extract 70mg (7%), Black Walnut Hull 30mg (3%), Prune Extract 100mg (10%), Aloe Vera 50mg (5%), L. Acidophilus 10mg (1%), Apple Pectin 40mg (4%), blended 1000mg.",
    extraInfo: "GMO-free",
    relatedProductsId: [1, 3, 4],
    optionsId: [1, 2, 3, 4, 5],
    price: { 1: 39.95, 2: 39.95 },
    imgSrc: "/images/Daily-Herbals-Cleanse.jpeg",
  },
  {
    id: 3,
    name: "GenBrain",
    characteristics: [],
    description: "",
    extraInfo: "",
    relatedProductsId: [1, 2, 4],
    optionsId: [1, 2, 3, 4, 5],
    price: { 1: 39.95, 2: 39.95 },
    imgSrc: "/images/Daily-Gerbals-GenBrain.jpeg",
  },
  {
    id: 4,
    name: "Skincell Advanced",
    characteristics: [],
    description:
      "Ingredients: Water 158mg (15.8%), Cetearyl Alcohol 165mg (16.5%), Caprylic/Capric Triglycerides 67mg (6.7%), Glycerin 61mg (6.1%), Ceteareth 58mg (5.8%), Butyrospermum Parkii Butter 55mg (5.5%), Butylene Glycol 51mg (5.1%), Palmitoyl Oligopeptide 48mg (4.8%), Palmitoyl Tetrapeptide 46mg (4.6%), Octyldodecanol 41mg (4.1%), Ethyhexyl Palmitate 33mg (3.3%), Zea Mays Oil 31mg (3.1%), Tocopheryl Acetate 31mg (3.1%), Cholecalciferol 28mg (2.8%), Retinyl Palmitate 20mg (2%), Ascorbic Acid 19mg (1.9%), Pyridoxine HCl 15mg (1.5%), Silica 15mg (1.5%), Sodium Propoxyhydroxypropyl Thiosulfate Silica 14mg (1.4%), Carbomer 10mg",
    extraInfo: "",
    relatedProductsId: [1, 2, 3],
    optionsId: [1, 2, 3, 4, 5],
    price: { 1: 39.95, 2: 39.95 },
    imgSrc: "/images/Daily-Herbals-Skincell-Advanced.jpeg",
  },
  {
    id: 5,
    name: "CANADIAN OATS N' PROTEIN",
    characteristics: [],
    description:
      "Oats n’ Protein was designed for the exact demands of on-the-go individuals who require a healthy dose of the highest quality (gluten-free) carbohydrates and high protein to stay full, focused, and fueled. Our convenient single serving cups are the ideal post-workout snack or commuter friendly breakfast, while our multi-serving 500g bags are the perfect balanced and customizable start to the day!",
    extraInfo: "",
    relatedProductsId: [1, 2, 3],
    optionsId: [6, 7, 8],
    price: { 1: 9.99, 2: 9.99 },
    imgSrc: "/images/quickOats.png",
  },
  {
    id: 6,
    name: "TRANS4ORM FAT BURNER POWDER",
    characteristics: [],
    description:
      "TRANS4ORM® is a scientifically-developed multi-stage thermogenic energizer and weight loss support supplement that works with your body to transform fat and build lean muscle.When reaching your weight loss goals, it is important to give your body all the tools it needs to support a faster metabolism, control appetite, with the energy, focus, and mood you need to perform at your best.Uncompromising quality standards backed up by researched ingredients, transparent formulas, and GMP certified.",
    extraInfo: "",
    relatedProductsId: [2,1, 3],
    optionsId: [6, 7, 8],
    price: { 1: 20.0, 2: 20.0 },
    imgSrc: "/images/transform.png",
  },
  {
    id: 7,
    name: "R1 CHARGED CREATINE SNOW CONE",
    characteristics: [],
    description:
      "R1 Charged Creatine’s refreshing fruit flavors are built to support an enhanced workout with hydration, energy, and greater training capacity.",
    extraInfo: "",
    relatedProductsId: [5, 6,9],
    optionsId: [6, 7, 8],
    price: { 1: 25.0, 2: 25.0 },
    imgSrc: "/images/creatin.png",
  },
  {
    id: 8,
    name: "SPORT COMPLEX “RULE ONE PROTEINS”",
    characteristics: [],
    description:
      "Better output means we obsess over the input. That is why Rule 1 Proteins™ maintains tight control over the entire process. From formulation and ingredients sourcing to blending and packaging. Everything is done the right way in our US – based, state-of-the-art facility. Streamlining and tightly controlling every phase of the process enables us to offer premium products without the premium price.",
    extraInfo: "",
    relatedProductsId: [5, 6,7],
    optionsId: [6, 7, 8],
    price: { 1: 130.0, 2: 130.0 },
    imgSrc: "/images/sportComplex.png",
  },
  {
    id: 9,
    name: "ALL 9 AMINO BCAAS & EAAS ORANGE CRANBERRY",
    characteristics: [],
    description:
      "With 10 grams total Essential Amino Acids (EAAs), including 7.2 grams of Branched Chain Amino Acids (BCAAs), ALL9 AminoTM is the ultimate goal-crushing muscle recovery formula. Experience the unrivaled and potent Essential Amino Acid formula in ALL9 that supports speedy muscle recovery and the Muscle Protein Synthesis process that is necessary for muscle growth.",
    extraInfo: "",
    relatedProductsId: [5, 6,7],
    optionsId: [6, 7, 8],
    price: { 1: 59.99, 2: 59.99 },
    imgSrc: "/images/amino.png",
  },
  {
    id: 10,
    name: "BCAA LEAN ENERGY BLUE RAZ",
    characteristics: [],
    description:
      "BCAA LEAN ENERGY is our most complete lean body performance fuel for anytime use with 5g of the highest quality BCAAs per serving combined with CLA, Acetyl-L-Carnitine and Maca Powder for fat burning and Beta-Alanine, L-Alanine and Taurine and to enhance endurance, recovery and focus. BCAA LEAN ENERGY uses natural energizers and antioxidants from Green Coffee and Green Tea for energy and focus. And if you’re on a low-carb or Keto diet, BCAA LEAN ENERGY can help support fat utilization and help fight fatigue often felt when in a calorie deficit. Make BCAA LEAN ENERGY your fuel for anytime energy, fat burning and performance.",
    extraInfo: "",
    relatedProductsId: [7,8,9],
    optionsId: [6, 7, 8],
    price: { 1: 14.99, 2: 14.99 },
    imgSrc: "/images/bcaa.png",
  },
  {
    id: 11,
    name: "SPORT COMPLEX “MASS POWER”",
    characteristics: [],
    description:
      "The Mass Power Sport Complex offers a comprehensive solution to enhance muscle development and support weight gain. With its protein-rich components and convenient protein bars, it provides a convenient and effective way to fuel your body for optimal performance and size gains.",
    extraInfo: "",
    relatedProductsId: [7,8,9],
    optionsId: [6, 7, 8],
    price: { 1: 149.99, 2: 149.99 },
    imgSrc: "/images/masspower.png",
  },
  {
    id: 12,
    name: "ISO100 HYDROLYZED WHEY",
    characteristics: [],
    description:
      "ISO100 is simply muscle-building fuel. If your goal is gaining muscle size and strength, then ISO100 is your perfect workout partner. Loaded with muscle-building amino acids, ISO100 can support even the most serious resistance-training programs.",
    extraInfo: "",
    relatedProductsId: [11,8,10],
    optionsId: [9, 10, 11],
    price: { 1: 79.99, 2: 79.99 },
    imgSrc: "/images/iso100.png",
  },
  {
    id: 13,
    name: "CLEAN MEAL SNICKERDOODLE",
    characteristics: [],
    description:
      "Never miss a meal again. Clean Meal™ is a quick and healthy meal replacement for people on the move. Scoop, shake, and, in just 60 seconds, you’ve got a complete meal packed with wholesome, whole-food nutrition: slow-burning carbs from Swedish oats and organic quinoa; organic coconut MCT oil; 21 vitamins and minerals from organic vegetables; and non-GMO whey protein isolate treated with ioWhey® technology for up to 123% better amino acid absorption*. Rich, creamy, and satisfying, reach for Clean Meal™ to replace up to two meals per day, or anytime you need a complete, nourishing meal on the go.",
    extraInfo: "",
    relatedProductsId: [10,11,12],
    optionsId: [9, 10, 11],
    price: { 1: 49.99, 2: 49.99 },
    imgSrc: "/images/cleanmeal.png",
  },
];

export const recomendedIdes = [4, 3, 2, 1];
export const bestsellersIdes = [1, 2, 3, 4];
